/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author prraf
 */
public class FrameVenda extends javax.swing.JFrame {
    int codVenda = 0;
    int contadorNota = 0;
    int qntProduto=0;
    float totalNota=0;
    //cria 50 prosutos possivel possiveis
    ProdutoClass[] produto = new ProdutoClass[50];
    VendaClass[] venda = new VendaClass[100];
    
       
    /**
     * Creates new form FrameVenda
     */
    public FrameVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbProduto = new javax.swing.JComboBox<>();
        txtValor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbQuantidade = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNota = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        cbPagamento = new javax.swing.JComboBox<>();
        ckEmitirNota = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REALIZAR VENDA");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("F:\\Fatec\\Terceiro Semestre\\Engenharia de Software II\\Trabalho_Engenharia_Software_II\\Gestao_de_Vendas\\mais.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("F:\\Fatec\\Terceiro Semestre\\Engenharia de Software II\\Trabalho_Engenharia_Software_II\\Gestao_de_Vendas\\ok.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Produto:");

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon("F:\\Fatec\\Terceiro Semestre\\Engenharia de Software II\\Trabalho_Engenharia_Software_II\\Gestao_de_Vendas\\cancel.png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Valor:");

        cbProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbProdutoItemStateChanged(evt);
            }
        });
        cbProduto.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cbProdutoInputMethodTextChanged(evt);
            }
        });
        cbProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProdutoActionPerformed(evt);
            }
        });
        cbProduto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbProdutoPropertyChange(evt);
            }
        });

        txtValor.setEditable(false);
        txtValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Quantidade:");

        cbQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNota.setColumns(20);
        txtNota.setRows(5);
        jScrollPane2.setViewportView(txtNota);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Método de Pagamento:");

        cbPagamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ckEmitirNota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckEmitirNota.setText("Emitir Nota");
        ckEmitirNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckEmitirNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(ckEmitirNota, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cbQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckEmitirNota))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int indiceDoCombo = cbProduto.getSelectedIndex();
        if(contadorNota==0){
            
            txtNota.setText("Cia da foto "+System.lineSeparator());
            txtNota.setText(txtNota.getText()+"Rua Doutor Milton Cruz, 120 - Centro - Mogi das Cruzes" +System.lineSeparator());
            txtNota.setText(txtNota.getText()+"CNPJ 01.758.666/0001-44 " +System.lineSeparator());
            txtNota.setText(txtNota.getText()+"Tel. (11) 4655-8866 " +System.lineSeparator()+System.lineSeparator());
            
            txtNota.setText(txtNota.getText()+"Descrição"+"\t"+"Valor Unitario"+"\t"+"Qntd"+"\t"+"Valor Total"+System.lineSeparator());
            contadorNota++;
        };
        float valorTotal = Float.parseFloat(txtValor.getText())* Float.parseFloat(cbQuantidade.getSelectedItem().toString());
        totalNota += valorTotal;
        qntProduto += Integer.parseInt(cbQuantidade.getSelectedItem().toString());
        txtNota.setText(txtNota.getText()+cbProduto.getSelectedItem().toString()+"\t"+txtValor.getText()+"\t"+cbQuantidade.getSelectedItem().toString()+"\t"+valorTotal+"\t"+System.lineSeparator());
        
                
        ;
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        venda[codVenda] = new VendaClass();
        venda[codVenda].codigo = codVenda;
        venda[codVenda].valorNota = totalNota;
        venda[codVenda].qntProdutos = qntProduto;
        venda[codVenda].pagamento = cbPagamento.getSelectedItem().toString();
        venda[codVenda].notaFiscal = ckEmitirNota.isSelected();
        
        
        
        System.out.println("Código da Nota: "+venda[codVenda].codigo);
        System.out.println("Valor da Nota: "+venda[codVenda].valorNota);
        System.out.println("Quantidades de Produtos da Nota: "+venda[codVenda].qntProdutos);
        System.out.println("Porma de Pagamento: "+venda[codVenda].pagamento);
        System.out.println("Emitir Nota Fiscal? "+venda[codVenda].notaFiscal);
        
        codVenda++;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        cbProduto.addItem("");
        for(int i=0;i<10;i++){
            if (i==0){
                produto[i] = new ProdutoClass();
                produto[i].nome = "Revelação 10x15";
                produto[i].valor  = 1.50;}
            else if (i==1){
                produto[i] = new ProdutoClass();
                produto[i].nome = "Revelação 13x18";
                produto[i].valor  = 2.50;}
            else if (i==2){
                produto[i] = new ProdutoClass();
                produto[i].nome = "Revelação 15x21";
                produto[i].valor  = 3.20;}
            else if (i==3){
                produto[i] = new ProdutoClass();
                produto[i].nome = "Revelação 20x30";
                produto[i].valor  = 8;}
            else if (i==4){
                produto[i] = new ProdutoClass();
                produto[i].nome = "Revelação 30x40";
                produto[i].valor  = 12;}
            else if (i==5){
                produto[i] = new ProdutoClass();
                produto[i].nome = "Porta Retrato 10x15";
                produto[i].valor  = 11.59;}
            else if (i==6){
                produto[i] = new ProdutoClass();
                produto[i].nome = "Porta Retrato 13x18";
                produto[i].valor  = 12.59;}
            else if (i==7){
                produto[i] = new ProdutoClass();
                produto[i].nome = "Porta Retrato 15x21";
                produto[i].valor  = 20.29;}
            else if (i==8){
                produto[i] = new ProdutoClass();
                produto[i].nome = "Porta Retrato 20x30";
                produto[i].valor  = 28.99;}
            else if (i==9){
                produto[i] = new ProdutoClass();
                produto[i].nome = "Porta Retrato 30x40";
                produto[i].valor  = 35.99;}
        cbProduto.addItem(produto[i].nome);
        }
        cbQuantidade.addItem("");
        for(int i=1;i<=10;i++){
            cbQuantidade.addItem(String.valueOf(i));
        }
        
        cbPagamento.addItem("");
        cbPagamento.addItem("Débito");
        cbPagamento.addItem("Crédito");
        cbPagamento.addItem("A Vista");
    }//GEN-LAST:event_formWindowActivated

    private void cbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProdutoActionPerformed
        // TODO add your handling code here:
        int i=0;
        if (cbProduto.getSelectedItem().toString()!=""){
            while(cbProduto.getSelectedItem().toString()!=produto[i].nome){
                i++;
            }
            txtValor.setText(String.valueOf(produto[i].valor)) ;
        }
        
        
    }//GEN-LAST:event_cbProdutoActionPerformed

    private void cbProdutoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbProdutoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProdutoPropertyChange

    private void cbProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbProdutoItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cbProdutoItemStateChanged

    private void cbProdutoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cbProdutoInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cbProdutoInputMethodTextChanged

    private void ckEmitirNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckEmitirNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckEmitirNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbPagamento;
    private javax.swing.JComboBox<String> cbProduto;
    private javax.swing.JComboBox<String> cbQuantidade;
    private javax.swing.JCheckBox ckEmitirNota;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtNota;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
